version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    networks:
      - app-tier

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.3-debian-11'
    networks:
      - app-tier
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092

  serverproducer:
    build: './ServerProducer'
    networks:
      - app-tier
    depends_on:
      - kafka


#  consumers:
#    build: './Consumer'
#    depends_on:
#      - kafka
#    networks:
#      - app-tier